# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Colors Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$cachylgreen =	rgba(82dcccff)
$cachymgreen =	rgba(00aa84ff)
$cachydgreen =	rgba(007d6fff)

$cachylblue =	rgba(01ccffff)
$cachymblue =	rgba(182545ff)
$cachydblue =	rgba(111826ff)

$cachywhite =	rgba(ffffffff)
$cachygrey =	rgba(ddddddff)
$cachygray =	rgba(798bb2ff)

$prettypink =	rgba(e18aaaff)

$pastelred = rgba(ff0055ff)
$pastelgray = rgba(333333ff)
$pastelgreen = rgba(a0ff20ff)
$pasteldgreen = rgba(309f20ff)
$pastelblue = rgba(2088ffff)


$pastelbase = rgba(FFC6FFff)
$pastelgray = rgba(282B3Eff)
$pastelgreen = rgba(A6E3A1ff)
$pasteldgreen = rgba(C8F7C5ff)
$pastelblue = rgba(89B4FAff)
