# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/#input

input {
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2
}

##used to make my toucpad non natural_scroll
device {
    name = elan1201:00-04f3:3098-touchpad
    natural_scroll = true
}
